version: '2'

volumes:
  peer0.org4.example.com:
  peer1.org4.example.com:
  peer2.org4.example.com:

networks:
  basic:

services:
  peer0.org4.example.com:
    container_name: peer0.org4.example.com
    extends:
      file: ./base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org4.example.com
      - CORE_PEER_LOCALMSPID=Org4MSP
      - CORE_PEER_ADDRESS=peer0.org4.example.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org4.example.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org4.example.com:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org4.example.com:10151
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb10:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    ports:
      - 10051:10051
    volumes:
      - /var/run/:/host/var/run/
      - ./org4-artifacts/crypto-config/peerOrganizations/org4.example.com/peers/peer0.org4.example.com/msp:/etc/hyperledger/fabric/msp
      - ./org4-artifacts/crypto-config/peerOrganizations/org4.example.com/peers/peer0.org4.example.com/tls:/etc/hyperledger/fabric/tls
      - peer0.org4.example.com:/var/hyperledger/production
    depends_on:
      - couchdb10
  couchdb10:
    container_name: couchdb10
    image: hyperledger/fabric-couchdb:0.4.18
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 14984:5984
    networks:
      - basic

  peer1.org4.example.com:
    container_name: peer1.org4.example.com
    extends:
      file: ./base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org4.example.com
      - CORE_PEER_LOCALMSPID=Org4MSP
      - CORE_PEER_ADDRESS=peer1.org4.example.com:10151
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10151
      - CORE_PEER_CHAINCODEADDRESS=peer1.org4.example.com:10152
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10152
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org4.example.com:10151
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer2.org4.example.com:10251
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb11:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    ports:
      - 10151:10151
    volumes:
      - /var/run/:/host/var/run/
      - ./org4-artifacts/crypto-config/peerOrganizations/org4.example.com/peers/peer1.org4.example.com/msp:/etc/hyperledger/fabric/msp/
      - ./org4-artifacts/crypto-config/peerOrganizations/org4.example.com/peers/peer1.org4.example.com/tls:/etc/hyperledger/fabric/tls
      - peer1.org4.example.com:/var/hyperledger/production
    depends_on:
      - couchdb11
  couchdb11:
    container_name: couchdb11
    image: hyperledger/fabric-couchdb:0.4.18
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 15984:5984
    networks:
      - basic

  peer2.org4.example.com:
    container_name: peer2.org4.example.com
    extends:
      file: ./base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer2.org4.example.com
      - CORE_PEER_LOCALMSPID=Org4MSP
      - CORE_PEER_ADDRESS=peer2.org4.example.com:10251
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10251
      - CORE_PEER_CHAINCODEADDRESS=peer2.org4.example.com:10252
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10252
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.org4.example.com:10251
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org4.example.com:10051
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb12:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    ports:
      - 10251:10251
    volumes:
      - /var/run/:/host/var/run/
      - ./org4-artifacts/crypto-config/peerOrganizations/org4.example.com/peers/peer2.org4.example.com/msp:/etc/hyperledger/fabric/msp
      - ./org4-artifacts/crypto-config/peerOrganizations/org4.example.com/peers/peer2.org4.example.com/tls:/etc/hyperledger/fabric/tls
      - peer2.org4.example.com:/var/hyperledger/production
    depends_on:
      - couchdb12
  couchdb12:
    container_name: couchdb12
    image: hyperledger/fabric-couchdb:0.4.18
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 16984:5984
    networks:
      - basic

  cli_Org4:
    container_name: cli_Org4
    image: hyperledger/fabric-tools:1.4.4
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=info
      - CORE_PEER_ID=cli_Org4
      - CORE_PEER_ADDRESS=peer0.org4.example.com:10051
      - CORE_PEER_LOCALMSPID=Org4MSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org4.example.com/users/Admin@org4.example.com/msp
      # Enable TLS
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org4.example.com/peers/peer0.org4.example.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org4.example.com/peers/peer0.org4.example.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org4.example.com/peers/peer0.org4.example.com/tls/ca.crt
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ./../chaincode/:/opt/gopath/src/github.com/chaincode
      - ./org4-artifacts/crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./config:/opt/gopath/src/github.com/hyperledger/fabric/peer/configtx
      - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts
    depends_on:
      - peer0.org4.example.com
      - peer1.org4.example.com
      - peer2.org4.example.com
    networks:
      - basic
  
  ca3:
    image: hyperledger/fabric-ca:1.4.4
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org4
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org4.example.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA4_PRIVATE_KEY
    ports:
      - "10054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org4.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA4_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./org4-artifacts/crypto-config/peerOrganizations/org4.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg4
    networks:
      - basic